Fixing old 404 pages [Removed]
GreenBayRules/quark-editor pull request #10
Opened 2018-04-04 05:06 UTC by Narulacodes

2018-04-04 14:39 UTC, Sheshank-s requested changes

2018-04-04 14:39 UTC, GreenBayRules commented on 404.html
> +   <style>
Still wrong, you need to close the style tag and the a element

2018-04-04 14:39 UTC, GreenBayRules commented on 404.html
> +
End h1 as well

2018-04-04 14:39 UTC, GreenBayRules commented on 404.html
> +<center>
You need to close <center>

2018-04-05 16:10 UTC, GreenBayRules commented
Please fix the rest of the comments i gave

2018-04-07 14:35 UTC, Narulacodes commented
i did

2018-04-07 14:36 UTC, Narulacodes commented on 404.html
> +<center>
close what? Body?

2018-04-07 23:55 UTC, merged

2018-04-08 00:00 UTC, MasterOfTheTiger commented
Finally it gets merged!

2018-04-08 00:10 UTC, GreenBayRules commented
Yeah lol