Create A 404 page
GreenBayRules/quark-editor pull request #8
Opened 2018-01-28 17:54 UTC by Narulacodes

2018-01-28 18:04 UTC, Sheshank-s requested changes

2018-01-28 18:04 UTC, GreenBayRules commented on 404.html
> +<p> The Page requested can't be found, If you thing this is wrong <a href="https://github.com/greenbayrules/quark-editor/issues/"> Create A Issue </a>
you need to add a closing </p> tag

2018-01-28 18:20 UTC, Narulacodes commented on 404.html
> +<p> The Page requested can't be found, If you thing this is wrong <a href="https://github.com/greenbayrules/quark-editor/issues/"> Create A Issue </a>
i did

2018-01-28 18:50 UTC, GreenBayRules commented on 404.html
> +<p> The Page requested can't be found, If you thing this is wrong <a href="https://github.com/greenbayrules/quark-editor/issues/"> Create A Issue </a>
</p> after the </a>

2018-01-28 19:50 UTC, Narulacodes commented on 404.html
> +<p> The Page requested can't be found, If you thing this is wrong <a href="https://github.com/greenbayrules/quark-editor/issues/"> Create A Issue </a>
oh opps

2018-01-28 20:07 UTC, GreenBayRules commented
Why remove styles.css?

2018-01-28 20:30 UTC, Narulacodes commented
because the style.css would collide with the custom one i made in head

2018-01-28 20:48 UTC, Sheshank-s requested changes

2018-01-28 20:48 UTC, GreenBayRules commented on 404.html
> +
you need to close the `</style>` tag

2018-03-27 23:30 UTC, callowaysutton commented
Seems good why not ship it?

2018-03-28 22:22 UTC, GreenBayRules commented
There are many errors, he didn't close the style tag, etc @callowaysutton

2018-03-28 22:22 UTC, GreenBayRules commented
Closing, as I doubt your going to do this @Narulacodes

2018-03-29 12:43 UTC, Narulacodes commented
i will! now!

2018-03-29 12:44 UTC, Narulacodes commented
Repoen so i can change it!

2018-04-01 18:34 UTC, closed without merging

2018-04-01 18:34 UTC, GreenBayRules commented
I'll do it myself

2018-04-01 22:15 UTC, MasterOfTheTiger commented
I would love to help, but what's the progress on yours?

2018-04-02 00:34 UTC, GreenBayRules commented
@MasterOfTheTiger Nah, it's okay I'm going to do this myself

2018-04-02 00:47 UTC, MasterOfTheTiger commented
Okay. Please tell me if there is anything I am able to help with in this repo.

2018-04-02 22:45 UTC, GreenBayRules commented
@MasterOfTheTiger Sure thanks! The only thing right now is adding support for Java and Python and I think @callowaysutton is on to that :D Thanks for the help!